substitutions:
  name: apollo-temp-pro-1
  version: "25.2.24.1"
  device_description: ${name} made by Apollo Automation - version ${version}.

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

api:
  services:
    - service: play_buzzer
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'
globals:
  - id: cycleCounter
    type: int
    restore_value: no
    initial_value: '0'
  - id: button_press_timestamp
    restore_value: no
    type: uint32_t
    initial_value: '0'

i2c:
  sda: GPIO16
  scl: GPIO17
  id: bus_a

web_server:  
  port: 80
  
ethernet:  
  type: W5500  
  clk_pin: GPIO10  
  mosi_pin: GPIO12 
  miso_pin: GPIO11
  cs_pin: GPIO9
  interrupt_pin: GPIO13
  reset_pin: GPIO14

one_wire:
  - platform: gpio
    pin: GPIO6

# Buzzer
output:
  - platform: ledc
    pin: GPIO8
    id: buzzer

rtttl:
  id: rtttl_buzzer
  output: buzzer


binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected
  - platform: gpio
    pin: 
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    id: reset_button

  - platform: template
    name: Temperature Within Range
    id: temp_within_range
    lambda: 'return (id(sht_temperature).state < id(max_temp).state) && (id(sht_temperature).state > id(min_temp).state) && id(alarm_outside_temp_range).state;'


sensor:
  - platform: internal_temperature
    name: "ESP Temperature"
    id: sys_esp_temperature

  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s

  - platform: sht4x_custom
    temperature:
      name: "Temperature"
      id: sht_temperature
    humidity:
      name: "Relative Humidity"
      id: sht_humidity


light:
  - platform: esp32_rmt_led_strip
    id: rgb_light
    name: "RGB Light"
    pin: GPIO4
    default_transition_length: 0s
    chipset: WS2812
    num_leds: 4
    rgb_order: grb
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 1000ms
          update_interval: 1000ms
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"

  - platform: factory_reset
    disabled_by_default: True
    name: "Factory Reset ESP"
    id: factory_reset_all

number:
  - platform: template
    id: min_temp
    name: Min Temperature
    min_value: -20
    max_value: 50
    step: 0.1
    unit_of_measurement: '°C'
    initial_value: -20
    optimistic: true
    update_interval: never
    mode: box

  - platform: template
    id: max_temp
    name: Max Temperature
    min_value: -20
    max_value: 50
    step: 0.1
    unit_of_measurement: '°C'
    initial_value: 200
    optimistic: true
    update_interval: never
    mode: box

switch:
  - platform: factory_reset
    id: factory_reset_switch
    internal: true
  - platform: gpio
    pin: GPIO5
    name: "Accessory Power"
    id: accessory_power
    restore_mode: ALWAYS_ON
    setup_priority: 1100
    internal: true
  - platform: template
    name: "Alarm Outside Temp Range"
    id: alarm_outside_temp_range    
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

interval:  
  - interval: 10s    
    then:
      if:
        condition:
          binary_sensor.is_off: temp_within_range
        then:
          - light.turn_off: rgb_light
          - lambda: id(rtttl_buzzer).play("siren:d=8,o=5,b=100:d,e,d,e,d,e,d,e;");


external_components:
  - source: github://ApolloAutomation/ExternalComponents
    components: [sht4x_custom] 

## TODO: Add Update
## TODO: Add Update Frequency Control
## TODO: Add Beep for outside temp/humidity range
## TODO: LED Blinks outside temp/humidity range
## TODO: LED range for yellow/red
## TODO: Add offset