substitutions:
  name: apollo-temp-pro-1 # TODO: Rename
  version: "24.8.7.2"
  device_description: ${name} made by Apollo Automation - version ${version}.

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

api:

globals:
  - id: cycleCounter
    type: int
    restore_value: no
    initial_value: '0'
  - id: button_press_timestamp
    restore_value: no
    type: uint32_t
    initial_value: '0'


web_server:
  port: 80

ethernet:
  type: W5500
  clk_pin: GPIO3
  mosi_pin: GPIO8
  miso_pin: GPIO2
  cs_pin: GPIO9