substitutions:
  name: apollo-temp-pro-1
  version: "24.10.31.2"
  device_description: ${name} made by Apollo Automation - version ${version}.

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

api:
  services:
    - service: play_buzzer
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'
globals:
  - id: cycleCounter
    type: int
    restore_value: no
    initial_value: '0'
  - id: button_press_timestamp
    restore_value: no
    type: uint32_t
    initial_value: '0'

i2c:
  sda: GPIO16
  scl: GPIO17
  id: bus_a

web_server:  
  port: 80
  
ethernet:  
  type: W5500  
  clk_pin: GPIO10  
  mosi_pin: GPIO12 
  miso_pin: GPIO11
  cs_pin: GPIO9
  interrupt_pin: GPIO13
  reset_pin: GPIO14

one_wire:
  - platform: gpio
    pin: GPIO6

# Buzzer
output:
  - platform: ledc
    pin: GPIO8
    id: buzzer

rtttl:
 output: buzzer

binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected
  - platform: gpio
    pin: 
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    id: reset_button

sensor:
  - platform: internal_temperature
    name: "ESP Temperature"
    id: sys_esp_temperature

  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s

  - platform: dallas_temp
    name: "Temperature Probe"
    update_interval: 5s
    id: temp_probe

  - platform: sht3xd
    temperature:
      name: "Probe Temperature"
    humidity:
      name: "Probe Humidity"
    address: 0x44
    update_interval: 60s

light:
  - platform: esp32_rmt_led_strip
    id: rgb_light
    name: "RGB Light"
    pin: GPIO4
    rmt_channel: 0
    default_transition_length: 0s
    chipset: WS2812
    num_leds: 4
    rgb_order: grb
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 1000ms
          update_interval: 1000ms
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"

  - platform: factory_reset
    disabled_by_default: True
    name: "Factory Reset ESP"
    id: factory_reset_all


switch:
  - platform: factory_reset
    id: factory_reset_switch
    internal: true


## TODO: Add Update
## TODO: Add Update Frequency Control
## TODO: Add Beep for outside temp/humidity range
## TODO: LED Blinks outside temp/humidity range
## TODO: LED range for yellow/red
## TODO: Add offset