esphome:
  name: "${name}"
  friendly_name: Apollo TEMP_PRO-1
  comment: Apollo TEMP_PRO-1
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ApolloAutomation.TEMP_PRO-1"
    version: "${version}"

  min_version: 2024.8.3

dashboard_import:
  package_import_url: github://ApolloAutomation/TEMP_PRO-1/Integrations/ESPHome/TEMP_PRO-1.yaml
  import_full_config: false



ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_managed

http_request:
  verify_ssl: true

safe_mode:

update:
  - platform: http_request
    id: firmware_update
    name: Firmware Update
    source: https://apolloautomation.github.io/TEMP_PRO-1/artifact/manifest.json


logger:

packages:
  core: !include Core.yaml
