name: Publish

on:
  push:
    branches:
      - main
    paths:
      - "**.yaml"

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  publish:
    uses: ApolloAutomation/Workflows/.github/workflows/publish.yml@main
    with:
      core_yaml_path: Integrations/ESPHome/Core.yaml
      firmwares_json: '[{"yaml": "Integrations/ESPHome/TEMP_PRO-1_ETH.yaml", "name": "firmware-e"}, {"yaml": "Integrations/ESPHome/TEMP_PRO-1_W.yaml", "name": "firmware-w"}]'