name: CI

on:
  pull_request:

permissions:
  # Allow GITHUB_TOKEN to add labels to pull requests
  pull-requests: write
  issues: write
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  label-check:
    uses: ApolloAutomation/Workflows/.github/workflows/label-check.yml@main
  ci:
    needs: [ label-check ]
    strategy:
      fail-fast: false
      matrix:
        file:
          - Integrations/ESPHome/TEMP_PRO-1_W.yaml
          - Integrations/ESPHome/TEMP_PRO-1_ETH.yaml
        esphome-version:
          - stable
          - beta
          - dev
    uses: ApolloAutomation/Workflows/.github/workflows/build.yml@main
    with:
      file: ${{ matrix.file }}
      esphome-version: ${{ matrix.esphome-version }}